title: Meteor React Tutorial
subtitle: React Tutorial
versions:
  - '1'
versioned-netlify-redirects:
  netlify_site_id: meteor-react-tutorial

logo:
  title:
  subtitle: React Tutorial

sidebar_categories:
  null:
    - index
    - changelog
  Simple Todos:
    - simple-todos/index
    - simple-todos/01-creating-app
    - simple-todos/02-collections
    - simple-todos/03-forms-and-events
    - simple-todos/04-update-and-remove
    - simple-todos/05-styles
    - simple-todos/06-filter-tasks
    - simple-todos/07-adding-user-accounts
    - simple-todos/08-methods
    - simple-todos/09-publications
    - simple-todos/10-running-on-mobile
    - simple-todos/11-testing
    - simple-todos/12-deploying
    - simple-todos/13-next-steps
  Simple Todos with GraphQL:
    - simple-todos-graphql/index
    - simple-todos-graphql/01-graphql-setup
    - simple-todos-graphql/02-especific-data
    - simple-todos-graphql/03-first-query
github_repo: 'meteor/react-tutorial'

url: http://react-tutorial.meteor.com/
root: /

source_dir: tutorial
content_root: tutorial

highlight:
  enable: false
